package fr.uv1.bettingServices;

import java.util.*;
import java.util.regex.*;

import fr.uv1.bettingServices.exceptions.*;

/**
 * 
 * @author Alban GOUGOUA & Henri-Michel KOUASSI <br>
 * <br>
 *         This class describes all the attributes and methods that one subscriber 
 *         could use on the betting software. <br>
 * 
 * @param lastName
 * 			The lastname of subscriber.
 * 
 * @param firstName
 * 			The firstname of subscriber.
 * 
 * @param userName
 * 			The username or pseudo of subscriber.
 * 
 * @param password
 * 			The password of subscriber.
 * 
 * @param tokenNumbers
 * 			The number of tokens of subscriber.
 * 
 * @param betsSubscriber
 * 			The list of bets of subscriber.
 * 			
 */
public class Subscriber {
	
	private String lastName;
	private String firstName;
	private String userName;
	private String password;
	private long tokenNumbers;
	
	private ArrayList<Bet> betsSubscriber;
	
	/**
	 * 
	 * Subscriber(String lastName, String firstName, String userName, String password) is the constructor of the class Subscriber.
	 * 
	 * @param lastName.
	 * 			The lastname of subscriber.
	 * 
	 * @param firstName
	 * 			The firstname of subscriber.
	 * 
	 * @param userName
	 * 			The username or pseudo of subscriber.
	 * 
	 * @param password
	 * 			The password of subscriber. This password is generated by the method subscribe of the class BettingSite.
	 * 
	 */
	public Subscriber(String lastName, String firstName, String userName, String password) {
		
		this.lastName = lastName;
		this.firstName = firstName;
		this.userName = userName;
		this.password = password;
		tokenNumbers = 0L;
		betsSubscriber = new ArrayList<Bet>();
	}
	
	/**
	 * 
	 * checks if the password input matches with the password of subscriber.
	 * 
	 * @param password
	 * 			The password input.
	 * 
	 * @throws AuthenticationException
	 * 			raised if the password input doesn't match with the password of subscriber.
	 * 
	 * @throws BadParametersException
	 * 			raised if password input doesn't respect the syntax of password.
	 * 
	 */
	public void authenticateSubscriber(String password) throws AuthenticationException, BadParametersException {
		
		boolean check = Pattern.matches("[a-zA-Z0-9]{8,}+", password);
    	
    	if(check == false) {
    		try {
    			throw new BadParametersException();
    		}
    		catch(BadParametersException e) {
    			System.out.println(e.pwdIncrorect());
    		}
    	}
		
    	else {
    		try {
    			if(this.password != password) throw new AuthenticationException();
    		}
    		catch(AuthenticationException e) {
    			System.out.println(e.getMessage());
    		}
    	}
	}
	
	/**
	 * changes the password of subscriber.
	 * 
	 * @param newPwd
	 * 			The new password input by the subscriber.
	 * 
	 * @param currentPwd
	 * 			The current password of subscriber.
	 * 
	 * @throws AuthenticationException
	 * 			raised if the currentPwd input doesn't match with the password of subscriber.
	 * 
	 * @throws BadParametersException
	 * 			raised if passwords input don't respect the syntax of password.
	 * 
	 */
	public void changeSubsPwd(String newPwd, String currentPwd) throws AuthenticationException, BadParametersException {
		
		boolean check1 = Pattern.matches("[a-zA-Z0-9]{8,}+", newPwd);
		boolean check2 = Pattern.matches("[a-zA-Z0-9]{8,}+", currentPwd);
		
		if((check1 == false) || (check2 == false)) {
			try {
				throw new BadParametersException();
			}
			catch(BadParametersException e) {
				System.out.println(e.pwdIncrorect());
			}
		}
		else {
			if(password != currentPwd) {
				try {
					throw new AuthenticationException();
				}
				catch(AuthenticationException e) {
					System.out.println(e.getMessage());
				}
			}
			else {
				password = newPwd;
			}
		}
	}
	
	/**
	 * checks if the debit is possible by the subscriber.
	 * 
	 * @param tokenToDebit
	 * 			The number of tokens to debiting on the number of tokens of subscriber.
	 * 
	 * @return true
	 * 			if the tokenToDebit is less than the number of tokens of subscriber.
	 * 
	 * @throws BadParametersException
	 * 			raised if the tokenToDebit is less than or equal 0.
	 * 
	 */
	public boolean isDebitPossible(long tokenToDebit) throws BadParametersException {
		
		if(tokenToDebit <= 0) {
			try {
				throw new BadParametersException();
			}
			catch(BadParametersException e) {
				System.out.println(e.tokensNumberIncorrect());
				return false;
			}
		}
		else {
			if(tokenNumbers >= tokenToDebit) return true;
			else return false;
		}
	}
	
	/**
	 * credit number of tokens of subscriber.
	 * 
	 * @param numberTokens
	 * 			The number of tokens to crediting.
	 * 
	 * @throws BadParametersException
	 * 			raised if the numberTokens is less than or equal to 0.
	 * 
	 */
	public void creditSubscriber(long numberTokens) throws BadParametersException {
		
		if(numberTokens <= 0) {
			try {
				throw new BadParametersException();
			}
			catch(BadParametersException e) {
				System.out.println(e.tokensNumberIncorrect());
			}
		}
		else {
			tokenNumbers += numberTokens ;
		}
	}
	
	/**
	 * debit number of tokens of subscriber.
	 * 
	 * @param numberTokens
	 * 			The number of tokens to debiting.
	 * 
	 * @throws BadParametersException
	 * 			raised if the numberTokens is less than or equal to 0.
	 * 
	 */
	public void debitSubscriber(long numberTokens) throws BadParametersException {
		
		if(numberTokens <= 0) {
			try {
				throw new BadParametersException();
			}
			catch(BadParametersException e) {
				System.out.println(e.tokensNumberIncorrect());
			}
		}
		else {
			tokenNumbers -= numberTokens ;
		}
	}
	
	/**
	 * add a bet in the list of bets of subscriber.
	 * 
	 * @param bet
	 * 			The bet to adding.
	 * 
	 */
	public void addBet(Bet bet) {
		
		betsSubscriber.add(bet);
	}
	
	/**
	 * cancel a bet of subscriber.
	 * 
	 * @param betDone
	 * 			The bet of subscriber to canceling.
	 * 
	 * @throws ExistingBetException
	 * 			raised if the betDone doesn't exist.
	 * 
	 * @throws BadParametersException
	 * 			raised if the numberTokens is less than or equal to 0.
	 *  
	 */
	public void cancelBet(Bet betDone) throws ExistingBetException, BadParametersException {
		
		long numberTokens = 0;
		
		for(Bet bet : betsSubscriber) {
			if(bet.equals(betDone)) {
				numberTokens = betDone.stake;
				betsSubscriber.remove(betDone);
			}
			else {
				try {
					throw new ExistingBetException();
				}
				catch(ExistingBetException e) {
					System.out.println(e.getMessage());
				}
			}
		}
		this.creditSubscriber(numberTokens);
	}
	
	/**
	 * cancel all bets of subscriber.
	 * 
	 * @throws BadParametersException
	 */
	public void cancelAllBets() throws BadParametersException { //Pas encore terminé
		
		betsSubscriber = new ArrayList<Bet>() ;
	}
	
	/**
	 * remove a bet of subscriber.
	 * 
	 * @param betToDelete
	 * 			The bet of subscriber to removing.
	 * 
	 * @throws BadParametersException
	 */
	public void removeBet(Bet betToDelete) throws BadParametersException { //Pas encore terminé
		
		for(Bet bet : betsSubscriber) {
			if(bet.equals(betToDelete)) {
				betsSubscriber.remove(betToDelete);
			}
		}
	}
	
	/**
	 * checks if a subscriber is equal to another subscriber.
	 * 
	 * @param subs
	 * 			The another subscriber.
	 * 
	 * @return true
	 * 			if the two subscribers have the same username or pseudo.
	 * 
	 * @throws ExistingSubscriberException
	 * 			raised if subs doesn't exist.
	 * 
	 */
	public boolean equals(Subscriber subs) throws ExistingSubscriberException { // Pas encore terminé.
		
		if(this.userName.equals(subs.userName)) return true;
		else return false;
	}
	
	/**
	 * give the information of subscriber.
	 * 
	 */
	public String toString() {
		
		String response = "Ce joueur s'appelle " + lastName +  " " + firstName + ", son nom d'utilisateur est "
				+ userName + " et il a " + tokenNumbers + " jetons." ;
		return response;
	}
	
	public static void main(String[] args) throws AuthenticationException, ExistingSubscriberException, BadParametersException {

		Scanner scan = new Scanner(System.in);
		Subscriber subs1 = new Subscriber("Alban", "GOUGOUA", "NABLA", "MonbonPetit");
		Subscriber subs2 = new Subscriber("Ange", "GOUGOUA", "Willy", "Zagbayou");
		System.out.println("Alban est-il Ange ? " + subs1.equals(subs2));
		System.out.println(subs1.toString());
		System.out.println(subs2.toString());
		System.out.println(subs1.isDebitPossible(10L));
		subs1.changeSubsPwd("albanDonald09", "MonbonPetit");
		scan.close();
	}
	
}
